# Generated by Django 5.1.6 on 2025-02-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='is_connected',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='luminosity',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='humidite',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='luminosite',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
    ]
