# Generated by Django 5.1.6 on 2025-02-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_sensordata_humidity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensordata',
            options={},
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='humidite',
            new_name='humidity',
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='luminosite',
            new_name='luminosity',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
