# Generated by Django 5.1.6 on 2025-02-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_sensordata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='soilHumidity',
            field=models.FloatField(default=0.0),
        ),
    ]
